<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<footer>
        <nav class="final">
            
        <a>Para entrar em contato:</a>
            <ul>
            
            <li>Contato:<a href="Contato.php">Pagina de contato</a></li>
            <li>github:<a href="https://github.com/FelipeESantana">FelipeESantana</a></li>
            <p class="fabio">E para quem nao sabe sou irmão gemeo desse animal aqui ==><a href="fabio.php">Fábio:)</a></p>
            <li class="copy">&copy;Todos os direitos reservados a -Felipe Eduardo Santana</li>
            </ul>
        </nav>
      
    </footer>
</body>
</html>