<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<header>
        <div class="topo">
            <nav class="titulo">
            <a>Quem Eu Sou?</a>
            </nav>
        
        <img src="eu.jpeg" id="minhaimg" alt="">

        </div>

    </header>
</body>
</html>
